jwt:
  time: 90000
  ret: hello-world123444

posco:
  name: 3기44444
  count: 2044444

test:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
