jwt:
  time: 904532523
  ret: hello-worl3245555
posco:
  name: 3542기
  count: 2044ㄱ33244
test:
  datasource:
    url: jdbc:mysql://?.?.?.?:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: rollin
    password: 1234
